# Book settings
title: Applied Deep Learning 2nd Edition - Online Companion
author: Umberto Michelucci and Michela Sperti
copyright: "TOELT LLC (2020-2021)"
logo: TOELT_ADL_2nd.png

repository:
  url                       : https://github.com/toelt-llc/ADL-Book-2nd-Ed
  path_to_book              : docs
  branch                    : master  

launch_buttons:
  colab_url: "https://colab.research.google.com"

html:
    home_page_in_navbar: false

latex:
  latex_documents:
    targetname: book.tex

execute:
  execute_notebooks: 'off'
